### ISSUE TITLE
Included JRE does not include JavaFX which breaks some plugins

### ISSUE THREAD

**Issue by wardev** [flathub/com.jetbrains.IntelliJ-IDEA-Community#43]
Some IDEA plugin, e.g. the ReDoc plugin require JavaFX to run. The JRE bundled in this flatpak does not include JavaFX so those plugins die with a `NoClassDefFoundError` as shown below. The bundled JRE should include all modules that were included in Java 8, including JavaFX.

```
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at com.phpinnacle.redoc.RedocPanel.<init>(RedocPanel.java:26)
	at com.phpinnacle.redoc.RedocEditor.<init>(RedocEditor.java:24)
	at com.phpinnacle.redoc.RedocApplication.createEditor(RedocApplication.java:55)
	at com.phpinnacle.redoc.RedocEditorProvider.createEditor(RedocEditorProvider.java:22)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.dumbModeFinished(FileEditorManagerImpl.java:213)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$300(FileEditorManagerImpl.java:106)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$2.lambda$exitDumbMode$0(FileEditorManagerImpl.java:159)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel PluginClassLoader[PluginDescriptor(name=Redoc, id=com.phpinnacle.redoc, path=/home/ward/.var/app/com.jetbrains.IntelliJ-IDEA-Community/data/JetBrains/IdeaIC2020.2/redoc, version=0.3)] com.intellij.ide.plugins.cl.PluginClassLoader@551f6cb4
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 34 more
```

**Comment by wardev** [comment]
I haven't used the flatpack in a while because of this issue.

**Comment by x80486** [comment]
Just to be clear. Do you have the exact same experience when using the non-Flatpak version?

**Comment by wardev** [comment]
No, I have Java 8 installed so it finds the JavaFX package.

**Comment by wardev** [comment]
Just tried it again today with:

```text
Name                            Application ID                                Version           Branch          Installation
IntelliJ IDEA Ultimate          com.jetbrains.IntelliJ-IDEA-Ultimate          2021.3.3          stable          user
```

and I still get the same error:

```text
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at com.phpinnacle.redoc.RedocPanel.<init>(RedocPanel.java:26)
	at com.phpinnacle.redoc.RedocEditor.<init>(RedocEditor.java:24)
	at com.phpinnacle.redoc.RedocApplication.createEditor(RedocApplication.java:55)
	at com.phpinnacle.redoc.RedocEditorProvider.createEditor(RedocEditorProvider.java:22)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.dumbModeFinished(FileEditorManagerImpl.java:287)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$1.lambda$exitDumbMode$0(FileEditorManagerImpl.java:184)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel PluginClassLoader(plugin=PluginDescriptor(name=Redoc, id=com.phpinnacle.redoc, descriptorPath=plugin.xml, path=~/.var/app/com.jetbrains.IntelliJ-IDEA-Ultimate/data/JetBrains/IntelliJIdea2021.3/redoc, version=0.3, package=null, isBundled=false), packagePrefix=null, instanceId=333, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 35 more
```

**Comment by zocker-160** [comment]
this issue can only be solved by adding OpenJFX / JavaFX to the Flatpak. 

Currently the IntelliJ tarball is being used which contains Java 11 JRE and thus does not include JavaFX (and never will).

**Comment by x80486** [comment]
> No, I have Java 8 installed so it finds the JavaFX package.

Right, so are effectively using a different Java SDK than the built-in one. I think this can be solved by modifying `entrypoint.sh` by checking (in reverse) the presence of `IDEA_JDK`, `JDK_HOME`, `JAVA_HOME`. In that case `IDEA_JDK` will be set only to the default value that it's right now.

Then you would need to provide an `override` for that environment variable in Flatpak; I guess it's something like `flatpak override --env=VAR=VALUE` — or something around those lines.
